apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kantheon

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: fuzzy
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: FUZZY_HTTP_PORT
            value: "7265"
          - name: FUZZY_GRPC_PORT
            value: "7266"
          - name: OTEL_SERVICE_NAME
            value: fuzzy
          - name: OTEL_ENABLED_FUZZY
            value: "false"
