ktor {
    deployment {
        port = "7110"
        port = ${?WHOIS_SERVER_PORT}
    }
    application {
        modules = []
    }
}

telemetry {
    enabled = false
    enabled = ${?OTEL_ENABLED_WHOIS}
    otlp {
        endpoint = "http://localhost:4317"
        endpoint = ${?OTEL_EXPORTER_OTLP_ENDPOINT}
    }
}

whois {
    repository {
        type = "json"
        type = ${?WHOIS_REPOSITORY_TYPE}
    }
    sync {
        keycloak {
            enabled = false
            enabled = ${?WHOIS_KEYCLOAK_SYNC_ENABLED}
            sync-users = true
            sync-users = ${?WHOIS_KEYCLOAK_SYNC_USERS}
            sync-roles = false
            sync-roles = ${?WHOIS_KEYCLOAK_SYNC_ROLES}
            sync-role-hierarchy = false
            sync-role-hierarchy = ${?WHOIS_KEYCLOAK_SYNC_ROLE_HIERARCHY}
            sync-user-role-mappings = false
            sync-user-role-mappings = ${?WHOIS_KEYCLOAK_SYNC_USER_ROLE_MAPPINGS}
            interval-seconds = 0
            interval-seconds = ${?WHOIS_KEYCLOAK_SYNC_INTERVAL}
        }
        erp {
            enabled = false
            enabled = ${?WHOIS_ERP_SYNC_ENABLED}
            sync-users = true
            sync-users = ${?WHOIS_ERP_SYNC_USERS}
            sync-roles = true
            sync-roles = ${?WHOIS_ERP_SYNC_ROLES}
            sync-role-hierarchy = true
            sync-role-hierarchy = ${?WHOIS_ERP_SYNC_ROLE_HIERARCHY}
            sync-user-role-mappings = true
            sync-user-role-mappings = ${?WHOIS_ERP_SYNC_USER_ROLE_MAPPINGS}
            interval-seconds = 0
            interval-seconds = ${?WHOIS_ERP_SYNC_INTERVAL}
        }
        entraid {
            enabled = false
            enabled = ${?WHOIS_ENTRAID_SYNC_ENABLED}
            sync-users = true
            sync-users = ${?WHOIS_ENTRAID_SYNC_USERS}
            sync-roles = true
            sync-roles = ${?WHOIS_ENTRAID_SYNC_ROLES}
            sync-role-hierarchy = true
            sync-role-hierarchy = ${?WHOIS_ENTRAID_SYNC_ROLE_HIERARCHY}
            sync-user-role-mappings = true
            sync-user-role-mappings = ${?WHOIS_ENTRAID_SYNC_USER_ROLE_MAPPINGS}
            interval-seconds = 0
            interval-seconds = ${?WHOIS_ENTRAID_SYNC_INTERVAL}
        }
    }
    cache {
        ttl-seconds = 300
        ttl-seconds = ${?WHOIS_CACHE_TTL_SECONDS}
    }
    jsonFilePath = ""
    jsonFilePath = ${?WHOIS_JSON_FILE_PATH}
    opaFilePath = "/mnt/opa"
    opaFilePath = ${?WHOIS_OPA_FILE_PATH}
}

who-is-database {
    type = "POSTGRES"
    type = ${?WHOIS_DB_TYPE}
    host = "localhost"
    host = ${?WHOIS_DB_HOST}
    port = "7432"
    port = ${?WHOIS_DB_PORT}
    database = "whois"
    database = ${?WHOIS_DB_NAME}
    user = "whois"
    user = ${?WHOIS_DB_USER}
    password = ""
    password = ${?WHOIS_DB_PASSWORD}
}

erp-database {
    type = "MSSQL"
    type = ${?ERP_DB_TYPE}
    host = "localhost"
    host = ${?ERP_DB_HOST}
    port = "1433"
    port = ${?ERP_DB_PORT}
    database = "ERP"
    database = ${?ERP_DB_NAME}
    user = "sa"
    user = ${?ERP_DB_USER}
    password = ""
    password = ${?ERP_DB_PASSWORD}
}

keycloak {
    host = "localhost"
    host = ${?KEYCLOAK_SERVER}
    port = "8443"
    port = ${?KEYCLOAK_SERVER_PORT}
    protocol = "https"
    protocol = ${?KEYCLOAK_PROTOCOL}
    realm = "df-test"
    realm = ${?KEYCLOAK_REALM}
    client-id = "whois"
    client-id = ${?KEYCLOAK_WHOIS_CLIENT_ID}
    client-secret = ""
    client-secret = ${?KEYCLOAK_WHOIS_CLIENT_SECRET}
    buffer-seconds = 30
    buffer-seconds = ${?KEYCLOAK_BUFFER_SECONDS}
    expires-in = 300
    expires-in = ${?KEYCLOAK_EXPIRES_IN}
}
