apiVersion: v1
kind: Service
metadata:
  name: {{ include "theseus-mcp.fullname" . }}
  labels:
    {{- include "theseus-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "theseus-mcp.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
