# SPDX-License-Identifier: Apache-2.0
"""ARC GATE 7 — the enrichment loop against a served stack (NLS-P9.3 T7).

Every other test in this arc holds something still. The unit suites run the
studio on SQLite with no front; the front's own component tier loads the real
snapshot with a *fixture* world overlay and no studio behind it. This one runs
the life of *Kauflandu* from LM detailed-design §9 across two processes, a
shared volume and a gRPC call, with nothing stubbed:

    a query misses  →  the front POSTs the token  →  the guesser proposes
    →  it auto-validates  →  the overlay is re-emitted into the shared volume
    →  the front is asked to reload  →  the SAME query now resolves, provisional
    →  a reviewer verifies  →  the rows are permanent, the provenance changes

What only this tier can catch is everything *between* the two services: that a
volume one writes is a volume the other can read, that the reload arrives, that
the front's fail-all loader survives an overlay being replaced underneath it,
and that the queue lands in a Postgres rather than in the SQLite the suite uses.

**One test for the walk, deliberately.** Its steps are not independent — each
one is the state the next begins from, and split into separate test functions
they raced (the miss generated by step 1 had already come back through the loop
by the time step 2 asked whether the word was still unknown). A lifecycle is a
sequence, so it is written as one.

Bring the stack up first — `docker-compose.gate7.yml` — then:

    GATE7_FRONT=localhost:7371 GATE7_STUDIO=http://localhost:7390 \\
      just test-py services/morph-studio -m component

⚑ Both env vars unset ⇒ skipped, like every other component test here. A gate
that silently passed because its subject was not running would be worse than
one nobody ran.
"""

from __future__ import annotations

import asyncio
import json
import os
import time
from pathlib import Path

import httpx
import pytest

pytestmark = pytest.mark.component

#: The sentence the demo is built on (`eval/cases/01-hero-compare.case.yaml`).
COMPARE = "Porovnej tržby Kauflandu za loňský rok s letošním"
#: The other hero — the one that reaches a `QueryPattern` (S-7).
INVOICES = "Zobraz všechny faktury od zákazníka Microsoft"

PIPELINE = "morph-patterns"

#: How long the loop is given to close. The front reloads on the studio's call,
#: so this bounds two RPCs and a file move — but the POST from the front's queue
#: sink leaves a background task, so the miss's *arrival* is genuinely async.
DEADLINE_S = 30.0


@pytest.fixture(scope="module")
def endpoints() -> tuple[str, str]:
    front = os.getenv("GATE7_FRONT", "")
    studio = os.getenv("GATE7_STUDIO", "")
    if not front or not studio:
        pytest.skip(
            "set GATE7_FRONT (host:port, gRPC) and GATE7_STUDIO (http base) — "
            "bring the stack up with `docker compose -f "
            "services/morph-studio/docker-compose.gate7.yml up -d`"
        )
    _ensure_stubs()
    _await_ready(front, studio)
    return front, studio


#: The wheel's generated `org.tatrman.{nlp,common}.v1` stubs, which are
#: gitignored and produced from `shared/proto`.
_WHEEL = Path(__file__).resolve().parents[4] / "shared" / "libs" / "python" / "ttr-nlp"
_STUB_MARKER = (
    _WHEEL / "generated" / "org" / "tatrman" / "nlp" / "v1" / "nlp_pb2_grpc.py"
)


def _ensure_stubs() -> None:
    """Generate the proto stubs, here and nowhere earlier.

    ⛑ This used to run at COLLECTION, in `tests/conftest.py`, the way `ttr-nlp`
    and `services/nlp` do it — and it turned morph-studio's CI job red:
    `grpcio-tools` is not in this service's dev group, so importing the conftest
    raised `ModuleNotFoundError: No module named 'grpc_tools'` and **the whole
    unit suite failed to load** over a dependency only this one component test
    needs. It passed locally only because `ttr-nlp`'s own suite had already
    written the stubs, so the `if not exists` guard never fired.

    Two things follow, and they are the fix:

    * It belongs **in the fixture that needs it**, not at import time. CI
      deselects `-m component`, so it now never runs there at all — which is
      right: generating protobuf stubs to *not* run a test is pure waste.
    * A missing compiler is a **skip with the command**, not an error. Somebody
      running the gate without the dev group has a setup problem, not a failure.
    """
    if _STUB_MARKER.exists():
        return
    try:
        import grpc_tools  # noqa: F401
    except ImportError:
        pytest.skip(
            "the org.tatrman.nlp.v1 stubs are absent and grpcio-tools is not "
            "installed — run `uv sync` in services/morph-studio, or generate "
            "them once with `cd shared/libs/python/ttr-nlp && uv run python "
            "scripts/gen_proto.py`"
        )
    import importlib
    import runpy

    try:
        runpy.run_path(str(_WHEEL / "scripts" / "gen_proto.py"), run_name="__main__")
    except SystemExit:
        # The script ends in `raise SystemExit(main())`; under `runpy` that
        # arrives here rather than exiting the interpreter.
        pass
    finally:
        # MANDATORY, and in a `finally` so a partial generation cannot skip it.
        # `pythonpath` puts `generated/` on `sys.path` before this runs; when
        # the directory does not exist yet the path finder caches that absence,
        # and creating it a moment later does not invalidate the cache — so
        # `import org.tatrman…` fails with `No module named 'org'` while the
        # stubs sit on disk in plain sight.
        importlib.invalidate_caches()


def _await_ready(front: str, studio: str, deadline: float = 90.0) -> None:
    """Wait for both services to answer before judging either.

    ⚑ `docker compose up -d` returns when the containers have STARTED, and the
    front then spends several seconds loading 25,097 rows. Without this the gate
    fails with `Connection refused` on whichever machine is slower that morning
    — a flake that says nothing about the thing under test, and the exact reason
    a gate stops being trusted.
    """
    end = time.monotonic() + deadline
    last = "?"
    while time.monotonic() < end:
        try:
            httpx.get(f"{studio}/readyz", timeout=5.0).raise_for_status()
            # ⚑ Not "does it answer" but "is it SERVING THE LEXICON". The port
            # opens before the 25k-row snapshot has loaded, and a `morph: true`
            # pipeline that answers at all is not yet proof — a core word coming
            # back `statistical` means the fallback is answering and the lexicon
            # is not there. Probing for that once, here, is what keeps the walk
            # from starting against a half-ready front and then failing thirty
            # seconds later somewhere unrelated.
            probe = analysis(run_pipeline(front, "rok"), "rok")
            if probe and probe.get("provenance") == "lexicon":
                return
            last = f"the front answers but is not serving the lexicon yet: {probe}"
        except Exception as exc:  # noqa: BLE001 — grpc's tree, plus httpx's
            last = f"{type(exc).__name__}: {exc}"
            time.sleep(1.0)
    pytest.fail(f"the gate-7 stack did not come up within {deadline:.0f}s — {last}")


@pytest.fixture(scope="module")
def studio(endpoints) -> httpx.Client:
    _, base = endpoints
    with httpx.Client(base_url=base, timeout=30.0) as client:
        yield client


@pytest.fixture
def fresh(studio):
    """The loop starts from a world that has never seen these words.

    Not a nicety: `rejected` is terminal and a verified entry is permanent, so a
    second run over the same database is measuring a different story. The fix is
    one command and the message says it.
    """
    body = studio.get("/v1/queue").raise_for_status().json()
    if body["items"]:
        pytest.skip(
            "the stack has already run this loop "
            f"({', '.join(i['token'] for i in body['items'][:3])}…). Reset it: "
            "`docker compose -f services/morph-studio/docker-compose.gate7.yml "
            "down -v && … up -d`"
        )


# ── talking to the stack ─────────────────────────────────────────────────────


async def _pipeline(front: str, text: str):
    from ttrnlp.client.grpc import NlpClient

    async with NlpClient(front) as client:
        return await client.run_pipeline(text, PIPELINE, language="cs")


def run_pipeline(front: str, text: str = COMPARE):
    return asyncio.run(_pipeline(front, text))


def analysis(result, form: str) -> dict | None:
    """The lexicon's answer for one surface form, or None if it missed.

    ⚑ Reads `Token.analyses` — the field that had no wire encoding at all until
    NLS-P9.1 gave each record a JSON string of its own. This assertion is the
    reason that encoding exists, so it is worth making through the wire rather
    than against the front's in-process document.
    """
    for token in result.document.annset("").with_type("Token"):
        if token.features.get("text") != form:
            continue
        raw = token.features.get("analyses") or []
        records = [json.loads(item) if isinstance(item, str) else item for item in raw]
        return records[0] if records else None
    return None


def types(result) -> set[str]:
    return {ann.type for ann in result.document.annset("")}


def wait_for(predicate, *, what: str, deadline: float = DEADLINE_S):
    """Poll until `predicate()` is truthy. The loop is asynchronous by design."""
    end = time.monotonic() + deadline
    last = None
    while time.monotonic() < end:
        last = predicate()
        if last:
            return last
        time.sleep(0.5)
    pytest.fail(f"timed out after {deadline:.0f}s waiting for {what} (last: {last!r})")


def queue_item(studio: httpx.Client, token: str) -> dict | None:
    body = studio.get("/v1/queue").raise_for_status().json()
    return next((item for item in body["items"] if item["token"] == token), None)


def learn(front: str, studio: httpx.Client, text: str, token: str) -> dict:
    """Drive one word all the way round the loop and verify it.

    Returns the queue item as it was when the cascade had finished with it —
    before the verdict, because that is the interesting state.
    """
    item = wait_for(
        lambda: queue_item(studio, token), what=f"{token} to reach the queue"
    )
    # ⚑ Not "an analysis exists" — the fallback always produces one. What the
    # loop changes is the PROVENANCE, so that is what is waited on.
    wait_for(
        lambda: (
            r
            if (r := analysis(run_pipeline(front, text), token))
            and r.get("provenance") != "statistical"
            else None
        ),
        what=f"{token} to resolve from the world overlay",
    )
    response = studio.post(f"/v1/queue/{item['id']}/verdict", json={"action": "verify"})
    response.raise_for_status()
    return item


# ── the walk ─────────────────────────────────────────────────────────────────


def test_the_life_of_kauflandu(endpoints, studio, fresh):
    """Detailed-design §9, across two processes and a shared volume."""
    front, _ = endpoints

    # ── 1. the served stack, before anything has happened ────────────────────
    #
    # One call, and both assertions come from it — which is what makes them
    # race-free: this is the request that GENERATES the miss, so at the instant
    # it was answered the word cannot already have been learned.
    first = run_pipeline(front, COMPARE)

    # Ordinary analytical vocabulary, straight from the released core.
    assert analysis(first, "tržby")["lemma"] == "tržba"
    assert analysis(first, "loňský")["lemma"] == "loňský"
    assert analysis(first, "letošním")["lemma"] == "letošní"
    # ⚑ And the world exists but is EMPTY — the seeded overlay doing its job.
    # Without it the front's fail-all loader would have dropped the whole Czech
    # lexicon over a file that did not exist yet (`_seed_overlay`).
    #
    # `Kaufland` is OPEN vocabulary and the core does not carry it (FI-1). A
    # core snapshot that answered here would be one that had absorbed somebody's
    # customer list; the miss is the input to the enrichment loop, not a gap.
    #
    # ⚑ A miss is not the ABSENCE of an analysis — it is one marked
    # `statistical`. The front's fallback still answers, with its own guess at
    # the lemma, and NLS-P7.3's finding is that this is the useful shape: the
    # miss IS the entity candidate, which is what a rule pack can lift and what
    # the queue reports. So the assertion is about provenance, and provenance is
    # exactly what changes twice in the steps below.
    missed = analysis(first, "Kauflandu")
    assert missed is not None
    assert missed["provenance"] == "statistical"

    # ── 2. the miss reached the studio, and the guesser met it ───────────────
    item = wait_for(
        lambda: queue_item(studio, "Kauflandu"),
        what="Kauflandu to reach the queue",
    )
    assert item["world"] == "dfp"
    assert item["verdict"] == "miss"
    assert item["status"] == "auto-validated"
    # LM-10: a proper noun routes to the world's entity layer, not the core.
    assert item["layer"] == "world"
    assert item["routed_by"] == "auto"

    best = item["cascade"]["proposals"][0]
    assert best["lemma"] == "Kaufland"
    assert best["upos"] == "PROPN"
    assert best["vzor"] == "hrad-proper"
    assert best["source"] == "guesser"
    assert item["cascade"]["tier"] == "guesser"

    # ── 3. Q-7: the same query now resolves, and says it is unconfirmed ──────
    #
    # ⚑ The assertion the whole arc is for. The overlay travelled through a
    # shared volume and the front was told to re-read it, so the query that
    # missed a moment ago answers — and the answer is FLAGGED, because nobody
    # has confirmed it.
    # ⚑ Waiting on the PROVENANCE, not on an analysis existing: the fallback
    # answers from the first request onwards, so "is there an analysis" is true
    # before the loop has done anything at all.
    record = wait_for(
        lambda: (
            r
            if (r := analysis(run_pipeline(front, COMPARE), "Kauflandu"))
            and r.get("provenance") != "statistical"
            else None
        ),
        what="Kauflandu to resolve from the provisional overlay",
    )
    assert record["lemma"] == "Kaufland"
    assert record["upos"] == "PROPN"
    assert record["provenance"] == "provisional"

    # ── 4. a reviewer verifies; the rows become permanent ────────────────────
    body = studio.post(
        f"/v1/queue/{item['id']}/verdict", json={"action": "verify"}
    ).raise_for_status().json()

    assert body["item"]["status"] == "verified"
    assert body["entry"]["status"] == "verified"
    assert body["entry"]["provisional"] is False
    assert body["overlay_emitted"] is True
    # The reload leg, over the wheel's own client, studio → front.
    assert "reloaded" in body["reload"], body["reload"]

    record = wait_for(
        lambda: (
            r
            if (r := analysis(run_pipeline(front, COMPARE), "Kauflandu"))
            and r.get("provenance") != "provisional"
            else None
        ),
        what="Kauflandu to serve as a permanent entry",
    )
    assert record["lemma"] == "Kaufland"
    assert record["provenance"] == "lexicon"

    # ── 5. a form nobody ever reported ───────────────────────────────────────
    #
    # The queue saw the genitive. What went into the overlay is the PARADIGM —
    # the engine generated every case from the pattern the guesser proposed — so
    # the instrumental resolves too, and nothing reported it. That is the whole
    # difference between a lexicon and a cache of answers.
    unseen = analysis(
        run_pipeline(front, "Porovnej tržby s Kauflandem za loňský rok"), "Kauflandem"
    )
    assert unseen is not None, "the generated paradigm did not reach the front"
    assert unseen["lemma"] == "Kaufland"
    assert unseen["provenance"] == "lexicon"

    # ── 6. "…→ NEXT query matches via the expanded world list" ───────────────
    #
    # ⚑ The gate's last step, and the arc's claim in one paragraph. The invoices
    # hero reaches a `QueryPattern` only when the customer's name is a PROPN the
    # rule pack can see, and the published core deliberately does not carry
    # customer names (FI-1). In the option lane NameTag supplies that; in this
    # stack there is no engine at all, so the ONLY thing that can make the
    # pattern fire is the world layer — and the world layer is built by the
    # loop. A query that could not be answered teaches the system the word it
    # was missing, and then can be answered.

    # The call that generates the miss, and its own answer as evidence.
    before = run_pipeline(front, INVOICES)
    assert analysis(before, "Microsoft")["provenance"] == "statistical", (
        "the fallback should be marking the unknown name as an entity candidate"
    )
    assert "QueryPattern" not in types(before), (
        "the pack cannot have fired yet — the world does not know this name"
    )

    learn(front, studio, INVOICES, "Microsoft")

    after = wait_for(
        lambda: (
            r if "QueryPattern" in types(r := run_pipeline(front, INVOICES)) else None
        ),
        what="the QueryPattern to fire over the expanded world",
    )
    (pattern,) = list(after.document.annset("").with_type("QueryPattern"))
    assert pattern.features["query"] == "faktury_zakaznika"
    assert pattern.features["nazev_zakaznika"] == "Microsoft"

    # And the name is now an ordinary lexicon entry with a part of speech.
    record = analysis(after, "Microsoft")
    assert record["upos"] == "PROPN"
    assert record["provenance"] == "lexicon"



def test_the_named_cases_hold_against_the_served_stack(endpoints):
    """The S-7 acceptance cases, re-run over gRPC instead of in-process.

    `ttr-morph eval` runs these against the artifact through the runtime loader;
    this runs the same expectations through the whole front — pipeline, wire
    encoding and all. Independent of the walk above: every word here is core
    vocabulary, so the world's state cannot change the answer.
    """
    front, _ = endpoints
    result = run_pipeline(front, COMPARE)

    expected = {
        "Porovnej": "porovnat",  # folded: the imperative is stored lowercase
        "tržby": "tržba",
        "za": "za",
        "loňský": "loňský",
        "rok": "rok",
        "s": "s",
        "letošním": "letošní",
    }
    for form, lemma in expected.items():
        record = analysis(result, form)
        assert record is not None, f"{form} had no analysis"
        assert record["lemma"] == lemma, form
        assert record["provenance"] == "lexicon", form


def test_the_export_gate_holds_on_the_served_stack(studio):
    """`POST /export` emits what a human verified and nothing below it."""
    body = studio.post("/v1/export", json={"write": False}).raise_for_status().json()

    files = body["files"]
    world = next((name for name in files if name.startswith("dfp")), None)
    assert world, f"no world layer file in {list(files)}"
    assert "license: world:dfp" in files[world]
    # Whatever the queue is still holding is held back BY STATUS, never by luck.
    assert all(
        status not in ("verified", "published") for status in body["withheld"]
    ), body["withheld"]
