// SPDX-License-Identifier: Apache-2.0
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Ready means the store answers. A studio that cannot reach its
         *     database is not degraded, it is unusable — every endpoint writes.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status__v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/machine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Machine
         * @description The LM-14 status machine, so the UI does not keep its own copy.
         *
         *     Same reasoning as `/v1/vzory`, applied to states instead of patterns:
         *     a frontend holding its own list draws chips for states that do not
         *     exist and offers a Verify button on an edge the machine refuses, and
         *     the reviewer finds out by getting a 409. Served, the buttons *are* the
         *     machine — a state added to `status.py` reaches them with no frontend
         *     release, and an invented one cannot appear.
         */
        get: operations["machine_v1_machine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/vzory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vzory
         * @description The closed inventory the UI's pattern picker is built from.
         *
         *     Served rather than hard-coded in the frontend for the reason the
         *     inventory is data in the first place (LM-2): a sub-vzor added to
         *     `vzory.yaml` has to reach the picker without a frontend release, or the
         *     analyst who needs it cannot choose it.
         */
        get: operations["vzory_v1_vzory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lookup/{form}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup */
        get: operations["lookup_v1_lookup__form__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entries */
        get: operations["list_entries_v1_entries_get"];
        put?: never;
        /** Create Entry */
        post: operations["create_entry_v1_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entry */
        get: operations["get_entry_v1_entries__entry_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{entry_id}/try-pattern": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Try Pattern
         * @description Generate a table for correction — contracts §7's `try-pattern`.
         */
        post: operations["try_pattern_v1_entries__entry_id__try_pattern_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{entry_id}/ask-llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask Llm
         * @description The classifier's proposal for an entry a human is looking at.
         */
        post: operations["ask_llm_v1_entries__entry_id__ask_llm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{entry_id}/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Forms */
        post: operations["correct_forms_v1_entries__entry_id__forms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entries/{entry_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Entry Status */
        post: operations["set_entry_status_v1_entries__entry_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest
         * @description The front's spool, or a direct POST (contracts §6/§7).
         */
        post: operations["ingest_v1_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Queue */
        get: operations["queue_v1_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/queue/{item_id}/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verdict */
        post: operations["verdict_v1_queue__item_id__verdict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export */
        post: operations["export__v1_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/export/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Export Proposals */
        post: operations["export_proposals_v1_export_proposals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CascadeModel
         * @description What the cascade concluded about a queue item.
         */
        CascadeModel: {
            /** Proposals */
            proposals: components["schemas"]["ProposalModel-Output"][];
            /**
             * Tier
             * @default human
             */
            tier: string;
            /**
             * Agreed
             * @default false
             */
            agreed: boolean;
            /** Notes */
            notes: string[];
        };
        /**
         * CorrectForms
         * @description `POST /entries/{id}/forms` — the edited table (FI-7 surface 2).
         *
         *     Sending a corrected table converts the entry to a full-form one at export:
         *     the pattern no longer describes it, and pretending otherwise is
         *     `LM-MORPH-005`.
         */
        CorrectForms: {
            /** Forms */
            forms: components["schemas"]["FormModel-Input"][];
            /**
             * Actor
             * @default human
             */
            actor?: string;
        };
        /** EntryModel */
        EntryModel: {
            /** Id */
            id: number;
            /** Lemma */
            lemma: string;
            /** Upos */
            upos: string;
            /** Layer */
            layer: string;
            /** Vzor */
            vzor: string | null;
            /** Flags */
            flags: string[];
            /** Status */
            status: string;
            /** Provenance */
            provenance: string;
            /** Source */
            source: string;
            /** Confidence */
            confidence: number;
            /** Provisional */
            provisional: boolean;
            /** Forms */
            forms: components["schemas"]["FormModel-Output"][];
        };
        /** ExportRequest */
        ExportRequest: {
            /**
             * Write
             * @default false
             */
            write?: boolean;
        };
        /** ExportResponse */
        ExportResponse: {
            /** Files */
            files: {
                [key: string]: string;
            };
            /** Written */
            written: string[];
            /**
             * Exported
             * @default 0
             */
            exported: number;
            /** Withheld */
            withheld: {
                [key: string]: number;
            };
        };
        /** FormModel */
        "FormModel-Input": {
            /** Form */
            form: string;
            /**
             * Feats
             * @default
             */
            feats?: string;
            /**
             * Corrected
             * @default false
             */
            corrected?: boolean;
        };
        /** FormModel */
        "FormModel-Output": {
            /** Form */
            form: string;
            /**
             * Feats
             * @default
             */
            feats: string;
            /**
             * Corrected
             * @default false
             */
            corrected: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IngestRequest */
        IngestRequest: {
            /** Reports */
            reports: components["schemas"]["Report"][];
        };
        /** IngestResponse */
        IngestResponse: {
            /**
             * Accepted
             * @default 0
             */
            accepted: number;
            /**
             * Created
             * @default 0
             */
            created: number;
            /**
             * Updated
             * @default 0
             */
            updated: number;
            /** Rejected */
            rejected: string[];
            /**
             * Overlay Emitted
             * @default false
             */
            overlay_emitted: boolean;
            /**
             * Reload
             * @default
             */
            reload: string;
        };
        /**
         * LookupResponse
         * @description Contracts §1's `LookupResult`, over HTTP.
         */
        LookupResponse: {
            /** Form */
            form: string;
            /** Matched Via */
            matched_via: string;
            /** Entries */
            entries: components["schemas"]["EntryModel"][];
        };
        /**
         * MachineResponse
         * @description The LM-14 status machine, as data (contracts §8).
         *
         *     Served for the same reason the pattern inventory is (`GET /v1/vzory`): a
         *     frontend that hard-codes the states draws chips for states that do not
         *     exist and offers buttons for edges the backend refuses, and the p9-3 task
         *     list asks for chips that "match the §8 machine exactly (no invented
         *     states)". A copy cannot be exact — only the thing itself can. So the UI
         *     renders what this returns, and a state added to `status.py` reaches the
         *     chips and the verdict buttons without a frontend release.
         */
        MachineResponse: {
            /** Statuses */
            statuses: string[];
            /** Transitions */
            transitions: {
                [key: string]: string[];
            };
            /** Exportable */
            exportable: string[];
            /** Terminal */
            terminal: string[];
            /** Actions */
            actions: string[];
            /** Layers */
            layers: string[];
        };
        /**
         * NewEntry
         * @description `POST /entries` — the "new word" affordance of FI-7 surface 2.
         *
         *     A `vzor` OR explicit `forms`, exactly as a layer file entry (contracts §3).
         *     Neither is required at creation: an analyst who has typed the word and its
         *     part of speech and wants to *try a pattern* next has entered something
         *     worth keeping.
         */
        NewEntry: {
            /** Lemma */
            lemma: string;
            /** Upos */
            upos: string;
            /**
             * Layer
             * @default core
             */
            layer?: string;
            /** Vzor */
            vzor?: string | null;
            /** Flags */
            flags?: string[];
            /** Forms */
            forms?: components["schemas"]["FormModel-Input"][];
            /**
             * Provenance
             * @default manual
             */
            provenance?: string;
            /**
             * Actor
             * @default human
             */
            actor?: string;
        };
        /**
         * ParadigmModel
         * @description A generated table, for review.
         */
        ParadigmModel: {
            /** Vzor */
            vzor: string;
            /** Flags */
            flags: string[];
            /** Forms */
            forms: components["schemas"]["FormModel-Output"][];
            /**
             * Validates
             * @default false
             */
            validates: boolean;
        };
        /**
         * PrecomputedCascade
         * @description A cascade that was already run — the NLS-P9.3 bootstrap batch's output.
         *
         *     `CascadeModel` plus the two fields the batch decided and the service would
         *     otherwise re-derive. They are separate here because on a *queue item* the
         *     status and the layer live on the item's own columns; this model is a
         *     request, and a request has to carry them.
         */
        PrecomputedCascade: {
            /** Proposals */
            proposals?: components["schemas"]["ProposalModel-Input"][];
            /**
             * Tier
             * @default human
             */
            tier?: string;
            /**
             * Agreed
             * @default false
             */
            agreed?: boolean;
            /** Notes */
            notes?: string[];
            /**
             * Status
             * @default proposed
             */
            status?: string;
            /**
             * Layer
             * @default core
             */
            layer?: string;
        };
        /**
         * ProposalModel
         * @description Contracts §7's `proposal` jsonb, one element.
         */
        "ProposalModel-Input": {
            /** Lemma */
            lemma: string;
            /** Upos */
            upos: string;
            /**
             * Vzor
             * @default
             */
            vzor?: string;
            /** Flags */
            flags?: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence?: number;
            /**
             * Source
             * @default guesser
             */
            source?: string;
        };
        /**
         * ProposalModel
         * @description Contracts §7's `proposal` jsonb, one element.
         */
        "ProposalModel-Output": {
            /** Lemma */
            lemma: string;
            /** Upos */
            upos: string;
            /**
             * Vzor
             * @default
             */
            vzor: string;
            /** Flags */
            flags: string[];
            /**
             * Confidence
             * @default 0
             */
            confidence: number;
            /**
             * Source
             * @default guesser
             */
            source: string;
        };
        /** QueueItemModel */
        QueueItemModel: {
            /** Id */
            id: number;
            /** World */
            world: string;
            /** Token */
            token: string;
            /** Verdict */
            verdict: string;
            /** Count */
            count: number;
            /** Context Span */
            context_span: string;
            /** Status */
            status: string;
            /** Layer */
            layer: string;
            /** Routed By */
            routed_by: string;
            /** Entry Id */
            entry_id: number | null;
            cascade: components["schemas"]["CascadeModel"];
        };
        /** QueueResponse */
        QueueResponse: {
            /** World */
            world: string;
            /** Items */
            items: components["schemas"]["QueueItemModel"][];
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * Report
         * @description One row of the front's spool (contracts §6), as `POST /ingest` takes it.
         */
        Report: {
            /** World */
            world: string;
            /** Token */
            token: string;
            /**
             * Verdict
             * @default miss
             */
            verdict?: string;
            /**
             * Count
             * @default 1
             */
            count?: number;
            /**
             * Context Span
             * @default
             */
            context_span?: string;
            /**
             * First Seen
             * @default
             */
            first_seen?: string;
            /**
             * Last Seen
             * @default
             */
            last_seen?: string;
            cascade?: components["schemas"]["PrecomputedCascade"] | null;
        };
        /** SetStatus */
        SetStatus: {
            /** Status */
            status: string;
            /**
             * Reason
             * @default
             */
            reason?: string;
            /**
             * Actor
             * @default human
             */
            actor?: string;
        };
        /** StatusResponse */
        StatusResponse: {
            /** World */
            world: string;
            /** Mode */
            mode: string;
            /** Ready */
            ready: boolean;
            /** Entries */
            entries: {
                [key: string]: number;
            };
            /** Queue */
            queue: {
                [key: string]: number;
            };
            /**
             * Llm
             * @default false
             */
            llm: boolean;
            /**
             * Provisional
             * @default false
             */
            provisional: boolean;
        };
        /**
         * TryPattern
         * @description `POST /entries/{id}/try-pattern` — generate, and optionally keep.
         */
        TryPattern: {
            /** Vzor */
            vzor: string;
            /** Flags */
            flags?: string[];
            /**
             * Apply
             * @default false
             */
            apply?: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verdict
         * @description `POST /queue/{id}/verdict` — FI-7 surface 3's three buttons.
         *
         *     `verify` promotes the entry (and makes any provisional overlay rows
         *     permanent); `reject` retracts; `route` is LM-10's human override and moves
         *     the entry between the core queue and the world's layer without judging it.
         */
        Verdict: {
            /** Action */
            action: string;
            /** Layer */
            layer?: string | null;
            /**
             * Reason
             * @default
             */
            reason?: string;
            /**
             * Actor
             * @default human
             */
            actor?: string;
        };
        /** VerdictResponse */
        VerdictResponse: {
            item: components["schemas"]["QueueItemModel"];
            entry: components["schemas"]["EntryModel"] | null;
            /**
             * Overlay Emitted
             * @default false
             */
            overlay_emitted: boolean;
            /**
             * Reload
             * @default
             */
            reload: string;
        };
        /**
         * VzorModel
         * @description One pattern of the closed inventory (LM-2, B-O5).
         */
        VzorModel: {
            /** Name */
            name: string;
            /** Upos */
            upos: string;
            /** Parent */
            parent: string | null;
            /** Implied Flags */
            implied_flags: string[];
            /** Hints */
            hints: {
                [key: string]: string | boolean;
            };
        };
        /**
         * VzoryResponse
         * @description `GET /vzory` — the pattern picker's whole world.
         *
         *     Typed rather than returned as a bare object: the picker is *constrained to
         *     the engine inventory*, and a response that generates as an index signature
         *     makes that a runtime hope instead of something the compiler checks.
         */
        VzoryResponse: {
            /** Language */
            language: string;
            /** Flags */
            flags: string[];
            /** Vzory */
            vzory: components["schemas"]["VzorModel"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    status__v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    machine_v1_machine_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MachineResponse"];
                };
            };
        };
    };
    vzory_v1_vzory_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VzoryResponse"];
                };
            };
        };
    };
    lookup_v1_lookup__form__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                form: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entries_v1_entries_get: {
        parameters: {
            query?: {
                status?: string | null;
                layer?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_v1_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_v1_entries__entry_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    try_pattern_v1_entries__entry_id__try_pattern_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TryPattern"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParadigmModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_llm_v1_entries__entry_id__ask_llm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParadigmModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_forms_v1_entries__entry_id__forms_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CorrectForms"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_entry_status_v1_entries__entry_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entry_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStatus"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_v1_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_v1_queue_get: {
        parameters: {
            query?: {
                world?: string | null;
                status?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verdict_v1_queue__item_id__verdict_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Verdict"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export__v1_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_proposals_v1_export_proposals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
