# SPDX-License-Identifier: Apache-2.0
"""Lists -> ``Lookup`` annotations. Deterministic, longest-match, unscored.

This is the layer that turns vocabulary into something a rule can match. It is
gatenlp's two gazetteers underneath, configured per list by its `matching` mode:

===================  ==============================================  ============
Mode                 Keyed on                                        Engine
===================  ==============================================  ============
``lemma``            the token's ``lemma`` feature, as written        Token trie
``ci``               the token's covered text, casefolded            Token trie
``fold-diacritics``  the covered text, casefolded AND unaccented     Token trie
``exact``            raw character run, no tokenization at all       String trie
===================  ==============================================  ============

**Why `lemma` is the interesting one.** Czech inflects: *faktura* appears as
*faktury*, *faktuře*, *fakturami*. A surface-text list would need every form of
every term, generated by something that already knows the morphology — at which
point the morphology may as well do the matching. So the list says the lemma and
the trie is keyed on the token's ``lemma`` feature, which the engine already
produced. One entry, all cases (contracts §4: "the Czech declension answer").

**Why `exact` bypasses tokens.** Codes and SKUs (``INV-2026/0042``) get split
differently by every tokenizer, so a token trie would match them only when the
tokenizer happened to agree with the list author. The string trie reads the raw
text. The cost is that a character trie will happily match inside a word, so
this mode adds a word-boundary guard of its own — see ``_string_matches``.

**Case folding is `mapfunc`, not a precomputed feature.** gatenlp's
``TokenGazetteer`` applies ``mapfunc`` to entry tokens when loading *and* to
document tokens when matching, which is exactly the symmetry these modes need,
so ``ci`` and ``fold-diacritics`` need nothing added to the importers. (The task
list allowed for a ``text_lower`` token feature if gatenlp had no such hook. It
has one, and one place doing the folding beats two places agreeing about it.)

**Longest-match, and skipping what it covers.** Both gazetteers run with
``longest_only=True`` *and* ``skip_longest=True``. The first makes "obchodní
zástupce" win over "obchodní" at the same start offset. The second matters just
as much and is easier to miss: without it, a list holding both "obchodní
zástupce" and "zástupce" annotates the phrase *and* its own tail, and a phase
whose ``input:`` is ``[Lookup]`` then sees an extra annotation sitting inside the
one the rule wanted — the coextensive-shadowing problem the hero pack's header
describes, arriving from the gazetteer instead of the pack. GATE's gazetteers
behave this way for the same reason.

**No scoring anywhere** (NL-17, and a grep gate in the P2.1 verify block asserts
it). A `Lookup` either matched or it did not.

**One trie per list.** Two lists are two knowledge sources: they may disagree,
they may overlap, and each carries its own provenance. Merging same-mode lists
into one trie would make longest-match arbitrate *between sources* — the longer
term wins and the other list's contribution vanishes with no diagnostic. Per
list, both fire and the pack author decides.
"""

from __future__ import annotations

import unicodedata
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, field

from gatenlp.processing.gazetteer import StringGazetteer, TokenGazetteer

from ttrnlp.doc.importers import TOKEN_TYPE
from ttrnlp.doc.model import Document
from ttrnlp.gazetteer.lists import GazetteerList, MatchingMode
from ttrnlp.packs.diag import NLS_PACK_003, DiagnosticCollector

#: Modes served by the token trie, and the token feature each is keyed on.
#: ``None`` means "the document text the token covers", which is what
#: ``tokentext_getter`` falls back to.
_TOKEN_MODES: dict[str, str | None] = {
    "lemma": "lemma",
    "ci": None,
    "fold-diacritics": None,
}


def casefold(text: str) -> str:
    """Case-insensitive key. ``casefold`` rather than ``lower`` — it folds the
    cases ``lower`` leaves alone (German ``ß``, Greek final sigma)."""
    return text.casefold()


def fold_diacritics(text: str) -> str:
    """Accent- and case-insensitive key: *zákazníka* and *zakaznika* agree.

    NFD splits each accented character into a base plus its combining marks;
    dropping the marks leaves the base letters. This is the glossary's ``*_ai``
    ("accent-insensitive") mode, and it folds case too — a list authored for
    people typing without a Czech keyboard is not also asking them to hold shift
    in the right places.
    """
    decomposed = unicodedata.normalize("NFD", text)
    stripped = "".join(ch for ch in decomposed if not unicodedata.combining(ch))
    return stripped.casefold()


_MAPFUNCS = {"ci": casefold, "fold-diacritics": fold_diacritics}


def _mapfunc(mode: MatchingMode):
    """The key function for a mode, or ``None`` to key on the value as written.

    ``lemma`` maps nothing on purpose: it is the one mode whose key comes from
    the engine rather than from the text, and the engine's lemma is already
    normalised the way that language normalises. Folding it as well would make
    `lemma` quietly mean "lemma, case-insensitively", leaving no mode that can
    tell *Microsoft* from *microsoft* on the lemma layer.
    """
    return _MAPFUNCS.get(mode)


def _provenance(source: GazetteerList) -> dict[str, str]:
    """The two features every Lookup carries (contracts §4, T4).

    Passed as gatenlp's *list* features rather than merged into each entry's:
    that keeps one copy per list instead of one per term, and the entry's own
    features cannot shadow them (an entry that tried is rejected at load —
    ``lists.RESERVED_FEATURES``).
    """
    return {"source": source.id, "matching": source.matching}


def _entry_tokens(term: str) -> list[str]:
    """Split a multi-token term the way ``TokenGazetteer`` splits its own.

    Whitespace, per gatenlp's default. A term whose own tokenization differs from
    the document's (``obchodní/zástupce`` versus a tokenizer that keeps the
    slash) will not match, which is a list-authoring problem with a visible
    symptom rather than a partial match with an invisible one.
    """
    return term.split()


def _build_token_gazetteer(source: GazetteerList) -> TokenGazetteer:
    entries = [(_entry_tokens(e.term), dict(e.features or {})) for e in source.entries]
    return TokenGazetteer(
        source=entries,
        source_fmt="gazlist",
        # `feature=None` keys on the covered document text; "lemma" keys on the
        # feature the engine produced.
        feature=_TOKEN_MODES[source.matching],
        mapfunc=_mapfunc(source.matching),
        longest_only=True,
        skip_longest=True,
        token_type=TOKEN_TYPE,
        ann_type=source.annotation,
        list_type=source.annotation,
        list_features=_provenance(source),
    )


def _build_string_gazetteer(source: GazetteerList) -> StringGazetteer:
    gazetteer = StringGazetteer(
        longest_only=True,
        skip_longest=True,
        ann_type=source.annotation,
    )
    gazetteer.append(
        source=[(e.term, dict(e.features or {})) for e in source.entries],
        source_fmt="gazlist",
        list_type=source.annotation,
        list_features=_provenance(source),
    )
    return gazetteer


def _is_word_char(ch: str) -> bool:
    return ch.isalnum() or ch == "_"


def _string_matches(gazetteer: StringGazetteer, doc: Document) -> int:
    """Run a string trie, keeping only matches that stand on their own.

    gatenlp's ``StringGazetteer.__call__`` annotates every match its trie finds,
    and its own ``match`` says so in a comment: *"this method does not check for
    any start condition (e.g. word start), the caller should do this!"* So a list
    holding the code ``INV-1`` would also annotate the ``INV-1`` inside
    ``XINV-12`` — a false positive with no diagnostic, in the one mode chosen
    precisely because codes must match exactly.

    Hence this replaces ``__call__``: same scan, but a match must not be flanked
    by word characters on either side. Punctuation, whitespace and the ends of
    the text are all fine boundaries, so ``(INV-1)`` and ``INV-1.`` still match.
    """
    text = doc.text
    annset = doc.annset("")
    added = 0
    for match in gazetteer.find_all(text):
        before = text[match.start - 1] if match.start > 0 else ""
        after = text[match.end] if match.end < len(text) else ""
        if _is_word_char(before) or _is_word_char(after):
            continue
        annset.add(match.start, match.end, match.type, features=dict(match.features))
        added += 1
    return added


@dataclass(frozen=True)
class Gazetteer:
    """Every configured list, ready to annotate.

    Built once and reused: the tries are the expensive part, and the service
    holds one of these per loaded pack state (NL-15's immutable snapshot).
    ``annotate`` mutates the document and nothing else, so one instance serves
    concurrent requests.
    """

    lists: tuple[GazetteerList, ...]
    _annotators: dict[str, TokenGazetteer | StringGazetteer] = field(repr=False)

    @property
    def list_ids(self) -> tuple[str, ...]:
        return tuple(source.id for source in self.lists)

    def annotate(self, doc: Document, *, lists: Sequence[str] | None = None) -> int:
        """Annotate ``doc`` in place; return how many annotations were added.

        Args:
            doc: The document to annotate. Tokens must already be there for
                every mode except ``exact``.
            lists: List ids to run, in the order given — a pipeline names its
                gazetteer step as a list of ids (contracts §7), and the order is
                the author's, not the config file's. ``None`` runs every list in
                the order they were loaded.

        Raises:
            KeyError: If a named list is not in this gazetteer. Callers that turn
                configuration into a run (the service) validate ids against
                ``list_ids`` first and report ``NLS-PACK-004`` instead.
        """
        chosen = self.list_ids if lists is None else tuple(lists)
        added = 0
        for list_id in chosen:
            annotator = self._annotators[list_id]
            if isinstance(annotator, StringGazetteer):
                added += _string_matches(annotator, doc)
            else:
                before = len(doc.annset(""))
                annotator(doc)
                added += len(doc.annset("")) - before
        return added


def build_gazetteer(lists: Iterable[GazetteerList]) -> Gazetteer:
    """Compile lists into a ``Gazetteer``.

    Args:
        lists: Validated lists, in the order they should run.

    Returns:
        A ``Gazetteer`` holding one trie per list.

    Raises:
        PackError: ``NLS-PACK-003`` if two lists share an id. Ids are how a
            pipeline names a list and how a Lookup records where it came from,
            so a duplicate makes both ambiguous — and the second list would
            silently replace the first here.
    """
    ordered = tuple(lists)
    collector = DiagnosticCollector()

    seen: set[str] = set()
    for source in ordered:
        if source.id in seen:
            collector.error(
                NLS_PACK_003,
                f"duplicate list id {source.id!r}: two lists cannot share an id — "
                "pipelines name lists by id and every Lookup records it as "
                "`source`",
            )
        seen.add(source.id)
    collector.raise_if_any()

    annotators: dict[str, TokenGazetteer | StringGazetteer] = {}
    for source in ordered:
        if source.matching in _TOKEN_MODES:
            annotators[source.id] = _build_token_gazetteer(source)
        else:
            annotators[source.id] = _build_string_gazetteer(source)

    return Gazetteer(lists=ordered, _annotators=annotators)


__all__ = ["Gazetteer", "build_gazetteer", "casefold", "fold_diacritics"]
