# SPDX-License-Identifier: Apache-2.0
"""The working store (contracts §7).

Revision ID: 0001
Revises:
Create Date: 2026-08-12

Hand-written rather than autogenerated, and kept in the shape the models
declare: `entry` · `entry_form` · `queue_item` · `audit`, with the two unique
constraints that carry the design — `(lemma, upos, layer)` for entry identity
(contracts §3, per LM-10 layer) and `(world, token)` for the queue, which is the
dedup key the front's own spool sink uses (contracts §6).

`jsonb` on Postgres, `json` elsewhere: `morph_studio.models.JsonB` is the same
variant, so the unit suite's SQLite database and a deployment's Postgres are the
same schema rather than two that happen to agree.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from morph_studio.models import JsonB

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "entry",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("lemma", sa.String(128), nullable=False),
        sa.Column("upos", sa.String(16), nullable=False),
        sa.Column("layer", sa.String(16), nullable=False),
        sa.Column("vzor", sa.String(64)),
        sa.Column("flags", JsonB, nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("provenance", sa.String(16), nullable=False),
        sa.Column("source", sa.String(16), nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("provisional", sa.Integer, nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("lemma", "upos", "layer", name="uq_entry_identity"),
    )
    op.create_index("ix_entry_status", "entry", ["status"])

    op.create_table(
        "entry_form",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "entry_id",
            sa.Integer,
            sa.ForeignKey("entry.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("form", sa.String(128), nullable=False),
        sa.Column("folded", sa.String(128), nullable=False),
        sa.Column("feats", sa.String(256), nullable=False),
        sa.Column("corrected", sa.Integer, nullable=False, server_default="0"),
        sa.UniqueConstraint("entry_id", "form", "feats", name="uq_entry_form"),
    )
    op.create_index("ix_entry_form_form", "entry_form", ["form"])
    op.create_index("ix_entry_form_folded", "entry_form", ["folded"])

    op.create_table(
        "queue_item",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("world", sa.String(64), nullable=False),
        sa.Column("token", sa.String(128), nullable=False),
        sa.Column("verdict", sa.String(32), nullable=False),
        sa.Column("count", sa.Integer, nullable=False),
        sa.Column("context_span", sa.Text, nullable=False),
        sa.Column("first_seen", sa.String(32), nullable=False),
        sa.Column("last_seen", sa.String(32), nullable=False),
        sa.Column("status", sa.String(32), nullable=False),
        sa.Column("proposal", JsonB, nullable=False),
        sa.Column("layer", sa.String(16), nullable=False),
        sa.Column("routed_by", sa.String(16), nullable=False),
        sa.Column(
            "entry_id", sa.Integer, sa.ForeignKey("entry.id", ondelete="SET NULL")
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("world", "token", name="uq_queue_item"),
    )
    op.create_index("ix_queue_item_status", "queue_item", ["world", "status"])

    op.create_table(
        "audit",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("subject", sa.String(32), nullable=False),
        sa.Column("subject_id", sa.Integer, nullable=False),
        sa.Column("action", sa.String(64), nullable=False),
        sa.Column("detail", JsonB, nullable=False),
        sa.Column("actor", sa.String(64), nullable=False),
    )
    op.create_index("ix_audit_subject", "audit", ["subject", "subject_id"])


def downgrade() -> None:
    op.drop_table("audit")
    op.drop_table("queue_item")
    op.drop_table("entry_form")
    op.drop_table("entry")
