CREATE TABLE IF NOT EXISTS jobs (
    id VARCHAR(255) PRIMARY KEY,
    status VARCHAR(50) NOT NULL,
    result VARCHAR(100000),
    request_payload VARCHAR(100000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS prompt_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255),
    model_name VARCHAR(255),
    provider VARCHAR(255),
    prompt_text VARCHAR(100000),
    response_text VARCHAR(100000),
    status VARCHAR(50),
    tokens_prompt INT,
    tokens_completion INT,
    duration_ms BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
